### PR TITLE
JPEG quality issues

### PR DESCRIPTION
**Pull request by sanchothefat**
There is some pretty bad artefacting going on, sharp has a default compression of 80% however even with a higher number a lot of fine detail is lost.

This approach involves delivering a double sized image but with more compression (40%) resulting in better detail on retina but a slightly larger file size.

Current solution takes an example image from 520kb to 95kb with huge degradation.

This solution takes the image from 520kb to 134kb with minimal degradation and sharper images.

@joehoyle I've experimented with a bit and we cold potentially go a bit lower on quality but this level seemed to strike a good balance.

### CODE REVIEW

**Comment by joehoyle** [comment]
Hmm I don't think we'd want to set this as the default as it's going to change the image size which is pretty unexpected when you ask for an image that is 800x600, is it possible to specify all this from the site (by hooking into tachyon-plugin)?

Also, do you have an example of the artifacted image?

**Comment by sanchothefat** [comment]
Yeah sorry, meant to add it:

**Original**



**Resized**



You can see especially around the detail eg the street sign and the 'Dior' lettering that it's very lossy.

While I don't *think* it'd break any existing uses I can see it'd make sense as a query param, I'll make the necessary changes.

**Comment by sanchothefat** [comment]
Another example of this technique http://gtmcknight.org/compression/

**Comment by willmot** [comment]
We were using this technique on the Human Made website originally as it provided better looking Retina images with much smaller filesizes

**Comment by sanchothefat** [comment]
@willmot cool :) Latest commit gives some control over it now anyway. The above images are a good example due to the typography and large smooth gradients of solid colour.

I've changed it so from the WP side we can filter the tachyon URL to say, if jpeg set scale to X and quality to Y.

What do you think?

**Comment by willmot** [comment]
Neat so you'd just pass `scale=2` to get a larger version back.

**Comment by joehoyle** [comment]
@sanchothefat are you on a retina device?

**Comment by sanchothefat** [comment]
@joehoyle yeah the macbook is and phone is. I'm not sure we can detect retina devices or high DPI devices though if that's what you're thinking, at least not here.

I guess we don't even need the scale arg if you think it's best just to filter in the WP plugin. Then the dims can be modified there and just the quality arg passed in.

**Comment by joehoyle** [comment]
Ok, I'm happy with this going in - Simple addition. However, i don't think this will fix https://github.com/unitedbloggers/unitedbloggers/issues/1296#issuecomment-215746057, it looks to me like that's an issue with selecting the right image from SRCSET, there's no way those awful quality images are a result of q=80 (I think)

**Comment by sanchothefat** [comment]
@joehoyle not sure you linked to the right issue on UI then but this should solve one of the main problems.

**Pull request merged**
